import { Area, MenuItem, Table, Order } from './types';

export const INITIAL_AREAS: Area[] = [
  { id: 'day_dau', name: 'Dãy đầu', badgeColor: 'bg-blue-100 text-blue-800 border-blue-200' },
  { id: 'day_giua', name: 'Dãy giữa', badgeColor: 'bg-purple-100 text-purple-800 border-purple-200' },
  { id: 'mang_xoi', name: 'Máng xối', badgeColor: 'bg-teal-100 text-teal-800 border-teal-200' },
  { id: 'ban_da', name: 'Bàn đá', badgeColor: 'bg-amber-100 text-amber-800 border-amber-200' },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Món chính
  {
    id: 'menu-1788788979675',
    name: 'Combo mỗi loại một cái',
    category: 'main',
    price: 48000,
    unit: 'Phần',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1TWukUCDXK4IBbPbCiaBYaeQcRR6z6GIP?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788784850670',
    name: 'Rau răm',
    category: 'main',
    price: 2000,
    unit: 'Đĩa',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1GFvC2nVOD-21PHkRvv0VpCakgSqiTFOf?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788754335014',
    name: 'Hành mềm',
    category: 'main',
    price: 8000,
    unit: 'Cái',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1N6qIlh8vn1kdRcPxkJNE2oXPWfKIqPc1?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788754313166',
    name: 'Hành giòn',
    category: 'main',
    price: 8000,
    unit: 'Cái',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1Ie58gSxjxVf88IGm_H8lCTPbwuCShuqS?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788753496659',
    name: 'Trứng đánh',
    category: 'main',
    price: 15000,
    unit: 'Cái',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1P9BcHWDtktjc9zlzN2K_hs-tATHUk17z?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788751947956',
    name: 'Ốp la',
    category: 'main',
    price: 15000,
    unit: 'Cái',
    isAvailable: true,
    image: 'https://thanhnien.mediacdn.vn/Uploaded/2014/saigonamthuc.thanhnien.com.vn/Pictures20136/HuongGiang/BanhtrangnuongDalat2.jpg',
  },

  // Đồ uống
  {
    id: 'menu-1788855403928',
    name: 'Tẩy đá',
    category: 'drink',
    price: 2000,
    unit: 'Ly',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/10lg5_KAZt3pKei6m9hKV8KyGu27I2RWZ?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788756339709',
    name: 'Khăn',
    category: 'drink',
    price: 2000,
    unit: 'Cái',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1JDroZq0bpqWkgL7NItYOr_m5otMJit7g?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788755744397',
    name: 'Trà đá',
    category: 'drink',
    price: 2000,
    unit: 'Ly',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1dgtIBPa9U07T3Tczz8DWDJZbibzO0vPs?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788755644509',
    name: '7up',
    category: 'drink',
    price: 15000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1xMOZpH9VMtEYm2pyMiMCrbsdgj1j2t4M?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788755566853',
    name: 'Bò húc',
    category: 'drink',
    price: 20000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/18gkVjWfnv4NesAYhp76VsPRE0xVGjMp9?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788755438179',
    name: 'C2 Chanh',
    category: 'drink',
    price: 15000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1IO6H6GA6OjdCUHBrR69ENFsjLO__iAub?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788755398908',
    name: 'C2 Đào',
    category: 'drink',
    price: 15000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1beoqxzZXToWgiisVT4cNWFD5Qiugb2l5?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788755241819',
    name: 'Ô long',
    category: 'drink',
    price: 15000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1uM399XuWULzRKjDM2N-7ZlyXFOl9t8gI?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788755170012',
    name: 'Trà xanh',
    category: 'drink',
    price: 15000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1pNKtL_XoMnkyVjaz4pVctKW61wyh4tli?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788754958419',
    name: 'Sting',
    category: 'drink',
    price: 15000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1zOALwsC9aJNUZgrOmjnlQKT8w747aL54?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-1788754856312',
    name: 'Pepsi',
    category: 'drink',
    price: 15000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1AmQ5GytpXFVnZ42o_UK69Rlsa5vkfVB6?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'd6',
    name: 'Coca',
    category: 'drink',
    price: 15000,
    unit: 'Lon',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1ufUWhmGFr8tC4g4iTaNmBo_a2PsDYGzE?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'd7',
    name: 'Nước suối',
    category: 'drink',
    price: 10000,
    unit: 'Chai',
    isAvailable: true,
    image: 'https://lh3.googleusercontent.com/d/1AWgVjWwetaT1RF-4PqWKNEdK6B9VFKlm?auto=format&fit=crop&w=400&q=80',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-g2',
    tableId: 't-g2',
    tableName: 'Bàn G2',
    areaId: 'day_giua',
    status: 'serving',
    customerCount: 4,
    createdAt: Date.now() - 45 * 60 * 1000, // 45 mins ago
    updatedAt: Date.now() - 15 * 60 * 1000,
    items: [
      {
        menuItemId: 'menu-1788751947956',
        name: 'Ốp la',
        price: 15000,
        quantity: 2,
        note: 'Nhiều tương ớt',
        image: 'https://thanhnien.mediacdn.vn/Uploaded/2014/saigonamthuc.thanhnien.com.vn/Pictures20136/HuongGiang/BanhtrangnuongDalat2.jpg',
      },
      {
        menuItemId: 'menu-1788753496659',
        name: 'Trứng đánh',
        price: 15000,
        quantity: 2,
        image: 'https://lh3.googleusercontent.com/d/1P9BcHWDtktjc9zlzN2K_hs-tATHUk17z?auto=format&fit=crop&w=400&q=80',
      },
      {
        menuItemId: 'menu-1788784850670',
        name: 'Rau răm',
        price: 2000,
        quantity: 1,
        image: 'https://lh3.googleusercontent.com/d/1GFvC2nVOD-21PHkRvv0VpCakgSqiTFOf?auto=format&fit=crop&w=400&q=80',
      },
      {
        menuItemId: 'menu-1788755744397',
        name: 'Trà đá',
        price: 2000,
        quantity: 4,
        image: 'https://lh3.googleusercontent.com/d/1dgtIBPa9U07T3Tczz8DWDJZbibzO0vPs?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'ord-mx1',
    tableId: 't-mx1',
    tableName: 'Bàn MX1',
    areaId: 'mang_xoi',
    status: 'waiting_payment',
    customerCount: 2,
    createdAt: Date.now() - 75 * 60 * 1000,
    updatedAt: Date.now() - 5 * 60 * 1000,
    items: [
      {
        menuItemId: 'menu-1788788979675',
        name: 'Combo mỗi loại một cái',
        price: 48000,
        quantity: 1,
        image: 'https://lh3.googleusercontent.com/d/1TWukUCDXK4IBbPbCiaBYaeQcRR6z6GIP?auto=format&fit=crop&w=400&q=80',
      },
      {
        menuItemId: 'menu-1788755644509',
        name: '7up',
        price: 15000,
        quantity: 2,
        image: 'https://lh3.googleusercontent.com/d/1xMOZpH9VMtEYm2pyMiMCrbsdgj1j2t4M?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
  {
    id: 'ord-d3',
    tableId: 't-d3',
    tableName: 'Bàn D3',
    areaId: 'day_dau',
    status: 'serving',
    customerCount: 3,
    createdAt: Date.now() - 20 * 60 * 1000,
    updatedAt: Date.now() - 10 * 60 * 1000,
    items: [
      {
        menuItemId: 'menu-1788754313166',
        name: 'Hành giòn',
        price: 8000,
        quantity: 3,
        image: 'https://lh3.googleusercontent.com/d/1Ie58gSxjxVf88IGm_H8lCTPbwuCShuqS?auto=format&fit=crop&w=400&q=80',
      },
      {
        menuItemId: 'd6',
        name: 'Coca',
        price: 15000,
        quantity: 3,
        image: 'https://lh3.googleusercontent.com/d/1ufUWhmGFr8tC4g4iTaNmBo_a2PsDYGzE?auto=format&fit=crop&w=400&q=80',
      },
    ],
  },
];

export const INITIAL_TABLES: Table[] = [
  // Dãy đầu (4 bàn)
  { id: 't-d1', name: 'Bàn D1', code: 'D1', areaId: 'day_dau', status: 'empty', capacity: 4 },
  { id: 't-d2', name: 'Bàn D2', code: 'D2', areaId: 'day_dau', status: 'empty', capacity: 4 },
  { id: 't-d3', name: 'Bàn D3', code: 'D3', areaId: 'day_dau', status: 'occupied', capacity: 6, currentOrderId: 'ord-d3', openedAt: Date.now() - 20 * 60 * 1000 },
  { id: 't-d4', name: 'Bàn D4', code: 'D4', areaId: 'day_dau', status: 'empty', capacity: 4 },

  // Dãy giữa (5 bàn)
  { id: 't-g1', name: 'Bàn G1', code: 'G1', areaId: 'day_giua', status: 'empty', capacity: 4 },
  { id: 't-g2', name: 'Bàn G2', code: 'G2', areaId: 'day_giua', status: 'occupied', capacity: 6, currentOrderId: 'ord-g2', openedAt: Date.now() - 45 * 60 * 1000 },
  { id: 't-g3', name: 'Bàn G3', code: 'G3', areaId: 'day_giua', status: 'empty', capacity: 4 },
  { id: 't-g4', name: 'Bàn G4', code: 'G4', areaId: 'day_giua', status: 'empty', capacity: 8 },
  { id: 't-g5', name: 'Bàn G5', code: 'G5', areaId: 'day_giua', status: 'empty', capacity: 4 },

  // Máng xối (4 bàn)
  { id: 't-mx1', name: 'Bàn MX1', code: 'MX1', areaId: 'mang_xoi', status: 'waiting_payment', capacity: 4, currentOrderId: 'ord-mx1', openedAt: Date.now() - 75 * 60 * 1000 },
  { id: 't-mx2', name: 'Bàn MX2', code: 'MX2', areaId: 'mang_xoi', status: 'empty', capacity: 6 },
  { id: 't-mx3', name: 'Bàn MX3', code: 'MX3', areaId: 'mang_xoi', status: 'empty', capacity: 4 },
  { id: 't-mx4', name: 'Bàn MX4', code: 'MX4', areaId: 'mang_xoi', status: 'empty', capacity: 8 },

  // Bàn đá (3 bàn)
  { id: 't-bd1', name: 'Bàn Đ1', code: 'Đ1', areaId: 'ban_da', status: 'empty', capacity: 10 },
  { id: 't-bd2', name: 'Bàn Đ2', code: 'Đ2', areaId: 'ban_da', status: 'empty', capacity: 8 },
  { id: 't-bd3', name: 'Bàn Đ3', code: 'Đ3', areaId: 'ban_da', status: 'empty', capacity: 10 },
];
